#!/bin/bash

cd {{ .ProjectSnake }}

# Set up the bazel_env
bazel build //tools:bazel_env

# Boot direnv
eval "$(direnv hook bash)"
direnv allow .
direnv reload
env
echo "$PATH" | tr ':' '\n'

# Format all Starlark files (i.e. BUILD, WORKSPACE, .bzl, or .sky) in this directory recursively
set +o errexit # ignore exit code
buildifier -r .  # Exits nonzero if it makes changes, and we expect that
set -o errexit

# Run the repin tool
repin

{{ if .Computed.js }}
which pnpm
pnpm install --lockfile-only
{{ end }}
