#!/usr/bin/env bash
# Example user workflows within an `aspect init`-generated repository
# where the C++ language is used.
set -o errexit -o pipefail -o nounset

# TODO(alex): create a cc_binary and run it
