#!/usr/bin/env bash
# Example user workflows within an `aspect init`-generated repository
# with the Java language enabled.

mkdir src
>src/Demo.java cat <<EOF
class Demo {
    public static void main(String[] args) {
        System.out.println("Hello from Java");
    }
}
EOF

# We didn't wire up the BUILD file generator for Java yet, so users
# are forced to write this manually.
>src/BUILD.bazel cat <<EOF
java_binary(name="Demo", srcs=["Demo.java"])
EOF

# Now the application should run
output="$(bazel run src:Demo)"

# Verify it produced the expected output
[[ "${output}" == "Hello from Java" ]] || {
    echo >&2 "Wanted output 'Hello from Java' but got '${output}'"
    exit 1
}
