#!/usr/bin/env bash
# Example user workflows within an `aspect init`-generated repository
# with the Kotlin language enabled.

mkdir src
>src/Demo.kt cat <<EOF
package app

class MyApp {
  companion object {
    @JvmStatic
    fun main(args: Array<String>) {
      println("Hello from Kotlin")
    }
  }
}
EOF

bazel run gazelle

# gazelle-prebuilt doesn't have Java support yet, so we have to do this manually
buildozer 'new java_binary app' src:__pkg__
buildozer 'set main_class app.MyApp' src:app
buildozer 'add runtime_deps :src' src:app

# Now the application should run
output="$(bazel run src:app)"

# Verify it produced the expected output
[[ "${output}" == "Hello from Kotlin" ]] || {
    echo >&2 "Wanted output 'Hello from Kotlin' but got '${output}'"
    exit 1
}
