#!/usr/bin/env bash
# Verify that the templated Bazel repository works with the 'shell' preset.
set -o errexit -o pipefail -o nounset

mkdir -p hello_world/src

# Create a tiny Rust program
cat >hello_world/src/main.rs <<EOF
fn main() { println!("Hello from Rust"); }
EOF

# We don't have any BUILD file generation for Rust yet,
# so users are forced to create it manually.
cat >hello_world/BUILD <<EOF
load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "hello_world",
    srcs = ["src/main.rs"],
)
EOF

# Run the program and assert that it produces the expected output
output="$(bazel run //hello_world)"
[[ "${output}" == "Hello from Rust" ]] || {
    echo >&2 "Wanted output 'Hello from Rust' but got '${output}'"
    exit 1
}
