#!/usr/bin/env bash
# Verify that the templated Bazel repository works with the 'shell' preset.
set -o errexit -o pipefail -o nounset

# Write a simple Bash executable
>hello.sh echo -e '#!/usr/bin/env bash\necho "Hello from Bash"'
chmod u+x hello.sh

# Generate BUILD files, see .aspect/cli/shell.star for the logic used
bazel configure || true

# Verify that running the Bash program produces the expected output
output="$(bazel run :hello)"
[[ "${output}" == "Hello from Bash" ]] || {
    echo >&2 "Wanted output 'Hello from Bash' but got '${output}'"
    exit 1
}
